### ISSUE TITLE
当数据更新很少的时候，屏幕上会重复出现最近几条数据。

### ISSUE THREAD

**Issue by icedfish** [icedfish/buswolves#1]
形如：
Uncaught Exception: Redis server went away in /home/data/lib/Redis/String.php on line 24
Uncaught Exception: in /home/data/lib/MongoData.php on line 94
Uncaught Exception: Redis server went away in /home/data/lib/Redis/Hash.php on line 72

Uncaught Exception: Redis server went away in /home/data/lib/Redis/String.php on line 24
Uncaught Exception: in /home/data/lib/MongoData.php on line 94
Uncaught Exception: Redis server went away in /home/data/lib/Redis/Hash.php on line 72

**Comment by icedfish** [comment]
补充下，好像是浏览器这边的问题，观察网络好像过程中没有发包过来。

**Comment by hax** [comment]
有确定的重现方式么？或者至少有高概率出现的方式？

**Comment by icedfish** [comment]
开一个数据比较少channel，开上几分钟，就会出现。
猜测是tcp连接超时之类的元婴被断开，然后客户端自动重连，导致buffer区域的数据会重新传输过来一次。

**Comment by hax** [comment]
是了，目前的默认状态是如果重连会重发buffer。想不重发的，可以在客户端重连的时候发送HTTP头Last-Event-ID，值为客户端最后接收到的事件id（即形如 id: xxx的行中的xxx）。
稍后会增加特性：允许创建channel的时候定义buffer，和默认没有Last-Event-ID的行为。
